### ISSUE TITLE
trending("star") fails with 0 results

### ISSUE THREAD

**Issue by aaccomazzi** [romanchyla/montysolr#73]
`trending("star")` currently returns 0 records, but other queries such as `trending("star formation")` work.  The SOLR logs do not show any error.

**Comment by romanchyla** [comment]
the problem here is that we are using 'score' to pick the first 200 results; and it happens to be all with empty 'reader' field

i tried using the classic_factor, it would make the query slower, but seems to produce results (quality of 
which i'm not able to judge)

try this: `trending(topn(200, star, classic_factor desc))`

opinions?

**Comment by romanchyla** [comment]
or another variation: `trending(topn(200, star, "pubdate desc, classic_factor desc"))`
